version: '2.1'

services:
  hypernode:
    build:
      context: ./../
      dockerfile: ./env/hypernode/Dockerfile
      args:
        - AUTH_APP_PWD=${AUTH_APP_PWD:-app}
        - AUTH_ROOT_PWD=${AUTH_ROOT_PWD:-root}
    environment:
      - SERVICE_ENV=test
    env_file:
      - ./../.env
    ports:
      - '${PORT_SSH:-2222}:22'
      - '${PORT_WEB:-8888}:80'
      - '${MYSQL:-3307}:3306'
      - '${PORT_MAILHOG:-8025}:8025'
    volumes:
      - './bin:/data/web/bin:delegated'
      - './shared:/data/web/shared:cached'
      - app-sync:${DEST_PATH:-/data/web/public}:nocopy
    image: '${PROJECT_NAME:-hdx}-hypernode:${BUILD_TAG:-latest}'
    container_name: '${PROJECT_NAME:-hdx}-hypernode'

volumes:
  app-sync:
    external:
      name: '${PROJECT_NAME:-hdx}-app-sync'