version: '2'

services:
  hypernode:
    build:
      context: ./../
      dockerfile: ./env/hypernode/Dockerfile
      args:
        - AUTH_APP_PWD=${AUTH_APP_PWD}
        - AUTH_ROOT_PWD=${AUTH_ROOT_PWD}
    image: '${COMPOSE_PROJECT_NAME}-hypernode:${COMPOSE_BUILD_TAG}'
    ports:
      - '${COMPOSE_PORT_SSH}:22'
      - '${COMPOSE_PORT_WEB}:80'
      - '${COMPOSE_PORT_MYSQL}:3306'
      - '${COMPOSE_PORT_MAILHOG}:8025'
    volumes:
      - './bin:/data/web/bin:delegated'
      - './shared:/data/web/shared:cached'
      - app-sync:${APP_VM_SOURCE}:nocopy

volumes:
  app-sync:
    external:
      name: '${COMPOSE_PROJECT_NAME}-app-sync'